version: '3'
services:
  app:
    build:
      context: .
    environment:
      - DICTIONARY=/var/dictionary.json
      - DISCORD_TOKEN=${TOKEN}
    volumes:
      - "./resources/dictionary.json:/var/dictionary.json:ro"
