version: '3'
services:
  app:
    build:
      context: .
    environment:
      - DICTIONARY=/var/dictonary.json
      - DISCORD_TOKEN=${TOKEN}
    volumes:
      - "./resources/dictonary.json:/var/dictonary.json:ro"
