name: Build

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        step: [ test, vet, fmt ]
    steps:
      - name: Cleanup workspace
        run: |
          echo "Cleaning up previous run from ${{ github.workspace }}"
          set -e # fail on error
          shopt -s dotglob # include hidden files
          sudo rm -rf *

      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: ${{ matrix.step }}
        run: docker run --rm --mount src=`pwd`,target=/go/service,type=bind golang:buster /bin/bash -c "cd /go/service && make ${{ matrix.step }}"

      - name: Remove docker image
        run: docker rmi golang:buster

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  build:
    name: build
    needs: [ test, lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v .

  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        archtype: [ linux/arm/v6, linux/arm/v7 ]
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: ${{ matrix.archtype }}
        run: |
          docker buildx build \
           --cache-from "type=local,src=/tmp/.buildx-cache" \
           --cache-to "type=local,dest=/tmp/.buildx-cache" \
           --platform ${{ matrix.archtype }} \
           --output "type=image,push=false" \
           --tag am3ocorp/discord-bot:latest \
           --tag am3ocorp/discord-bot:${GITHUB_REF#refs/tags/} \
           --file ./Dockerfile ./

      - name: Inspect image
        run: |
          docker buildx imagetools inspect am3ocorp/discord-bot:latest
          docker buildx imagetools inspect am3ocorp/discord-bot:${GITHUB_REF#refs/tags/}
